-- UPDATE image_sync_records
-- SET input_order=0;
-- 
-- UPDATE image_sync_records
-- SET duration = 0;
-- 
-- UPDATE image_sync_records
-- SET started_at = CURRENT_TIMESTAMP;
-- 
-- UPDATE image_sync_records
-- SET completed_at = CURRENT_TIMESTAMP;
-- 
-- UPDATE image_sync_records
-- SET created_at = CURRENT_TIMESTAMP;
-- 
-- UPDATE image_sync_records
-- SET updated_at = CURRENT_TIMESTAMP;
-- 
-- UPDATE image_sync_records 
-- SET original_input = CASE 
--     -- 如果架构是arm64，则添加--platform=linux/arm64前缀
--     WHEN architecture = 'arm64' THEN 
--         CASE 
--             WHEN tag IS NOT NULL AND tag != '' THEN CONCAT('--platform=linux/arm64 ', original_image, ':', tag)
--             ELSE CONCAT('--platform=linux/arm64 ', original_image)
--         END
--     -- 其他架构（主要是amd64）直接使用镜像名
--     ELSE 
--         CASE 
--             WHEN tag IS NOT NULL AND tag != '' THEN CONCAT(original_image, ':', tag)
--             ELSE original_image
--         END
-- END,
-- updated_at = CURRENT_TIMESTAMP
-- WHERE original_input IS NULL OR original_input = '';
-- 
-- 
-- 
-- -- 找出重复项(镜像名称+tag+架构)
-- SELECT 
--     id,
--     original_image,
--     tag,
--     architecture
-- FROM 
--     image_sync_records
-- WHERE 
--     (original_image, tag, architecture) IN (
--         SELECT 
--             original_image,
--             tag,
--             architecture
--         FROM 
--             image_sync_records
--         WHERE 
--             deleted_at IS NULL  -- 如果只查找未被删除的记录
--         GROUP BY 
--             original_image, 
--             tag, 
--             architecture
--         HAVING 
--             COUNT(*) > 1
--     )
-- ORDER BY 
--     original_image, 
--     tag, 
--     architecture;
